[[pages]]
path = "_ğŸ«_Home.py"
name = "Home"

[[pages]]
path = "pages/1_ğŸ—ƒï¸_Dataset.py"
name = "Dataset"

[[pages]]
path = "pages/2_ğŸ”_AnÃ¡lise.py"
name = "AnÃ¡lise"

[[pages]]
path = "pages/3_ğŸ“Š_Modelo.py"
name = "Modelo"

[[pages]]
path = "pages/4_ğŸ“_FormulÃ¡rio_APV.py"
name = "FormulÃ¡rio_APV"

[[pages]]
path = "pages/5_ğŸ“–_ReferÃªncias.py"
name = "ReferÃªncias"